### ISSUE TITLE
[Question] How to add "hostname" attribute to CertificationRequestInfo?

### ISSUE THREAD

**Issue by Geobert** [Devolutions/picky-rs#77] opened 2021-02-22 16:08 UTC
Hi,

We first used `Csr::generate` to create a csr but now we'd like to add a hostname in it so I've duplicated the code of generate in order to modify the `CertificationRequestInfo`. But looking at the documentation, I have no clue on how to add an "hostname" attribute and its value.

Thank you for any insight :D

**Comment by CBenoit** [comment] 2021-02-22 20:18
Hi @Geobert,

I assume you're referring to [CertificateRequestInfo attributes field](https://tools.ietf.org/html/rfc2986#section-4)?
These are not yet supported by picky: [certification_request.rs#L20](https://github.com/Devolutions/picky-rs/blob/master/picky-asn1-x509/src/certification_request.rs#L20)

**Comment by Geobert** [comment] 2021-02-23 08:57
Thank you for your answer!

> These are not yet supported by picky :/ (see certification_request.rs#L20)

I see, is there any plan to support them and when?

**Comment by CBenoit** [comment] 2021-02-23 13:54
> Thank you for your answer!
> 
> > These are not yet supported by picky :/ (see certification_request.rs#L20)
> 
> I see, is there any plan to support them and when?

I'm afraid to say there is no plan because no one needs that at @Devolutions AFAIK. However, I would gladly accept and review PR to improve on that :slightly_smiling_face:

**Comment by Geobert** [comment] 2021-02-24 15:41
>  I would gladly accept and review PR to improve on that 🙂

Hi, thank you for your answer!

What would it take to add support to add attributes to a CSR?

Looking at the code, I'm not sure how to modify the `attributes` field.
My first guess is to change its type for something like `Implicit<Option<Something>>`
`Something` being a type that can store a key and its value, ordered and serializable to DER.

Am I on the right track?

**Comment by CBenoit** [comment] 2021-02-24 16:26
> > I would gladly accept and review PR to improve on that slightly_smiling_face
> 
> Hi, thank you for your answer!
> 
> What would it take to add support to add attributes to a CSR?
> 
> Looking at the code, I'm not sure how to modify the `attributes` field.
> My first guess is to change its type for something like `Implicit<Option<Something>>`
> `Something` being a type that can store a key and its value, ordered and serializable to DER.
> 
> Am I on the right track?

Exactly, you are on the right track! :+1: 

Looking at the RFC I see this is behind Application Tag 0 (notice [0])

![image](https://user-images.githubusercontent.com/3809077/109026859-33b70c80-768e-11eb-98bd-9a5e127e9d8a.png)

As such this should probably be something like
```
pub attributes: Implicit<Option<ApplicationTag0<Something>>>,
```

Currently `Something` is () which is used for [NULL tag](https://docs.rs/picky-asn1/0.3.1/src/picky_asn1/lib.rs.html#14-17).

Maybe `Something` will be something like [`AttributeTypeAndValue`](https://github.com/Devolutions/picky-rs/blob/master/picky-asn1-x509/src/attribute_type_and_value.rs#L22).

Additionally you'll probably find it useful to generate a certification request using `openssl` or another similar tool and inspect DER encoding using a website like [this one](https://lapo.it/asn1js/#MIICYjCCAUoCAQAwHTEbMBkGA1UEAxMSdGVzdC5jb250b3NvLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAym0At2TvEqP0mYVLJzGVpNXjugu_kBpuKvXt_Vax4Bxnj3YzHTCpwkyZPytUC6zJ-q-uGh0e7gYQsYHJKjgoKEsS6gQ4ZM3D_AQy0zqPUT0ruSKDWKK4f2d_2ijDs5R2LHj7DtNZBanCXU16Qp1O28su0QZKOYbXzsJSpHp80dhqD6JUxXlSZzlVBp28CC9ryrE6w-kOQ38TZ1_mBJPsfmDeKBpm3FRrfHtWt43eok_T6FhCLIzsqyCZ0UCQqkcLr-TfoftJe2nOHQ1sfk4keJ9iwA_fhYv5rqUB3RUztSIhExwtYDwd-YovenhsL4sW_kjR29RTLUFPPXAelG9XPwIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAKrCf4sFDBFZQ6CPYdaxe3InMp7KFaueMIB8_YK73rJ-JGB6fQfltCCkToTE1y0Q3UqTlqHmaqdoh0KMWue6jCFvBat4_TUqUG7WtRLDP67eMulolcIzLqwTjR38DVJvnwrd2pey43q3UHBjlStxT_gI4ysQHn4qrzHB6OK9O6ypqTtwXxnm3TJF9dctLwvbh7NZSaamSlxI0_ajKZOP9k1KZEOPtaiiMPe2yr-QvwY2ov66MRG5PPRZELQWBaPZOuFwmCsFOLXJMpvhoAgklBCFZmiQMgApGIC1FIDgjm2ZhQQIRMnTsAV6f7BclRTaUkc0sPl17YB9GfNfOm1oL7o).

**Comment by Geobert** [comment] 2021-02-25 14:15
Thank you again for your insight. 

After reading the RFC, I'm leaning towards `Something` being `HashSet<CriAttribute>` with:
```rust
pub struct CriAttribute {
  pub ty: ObjectIdentifierAsn1,
  pub values: HashSet<ExtensionValue>,
}
```

So we'll end up with:
```rust
pub attributes: Implicit<Option<ApplicationTag0<HashSet<CriAttribute>>>>,
```
Does this sound right to you?

**Comment by CBenoit** [comment] 2021-02-25 16:57
Are you referring to Rust `std::collections::HashSet`? You should use [`Asn1SetOf`](https://docs.rs/picky-asn1/0.3.1/picky_asn1/wrapper/struct.Asn1SetOf.html) for ASN1 sets.

I tried to generate a certificate sign request using openssl with this command
```
openssl req -newkey rsa:2048
```

I answered `test` to `An optional company name` question.
Here is the [DER in asn1js](https://lapo.it/asn1js/#MIICnzCCAYcCAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALNNz0gw7Ftk13xy_cJ6gSqpCze_8cNVP7-PtrLeXNEbCwR0p1QnUEQysrvymbz2RQ0AZnEWAgVm7E6X2I56DA-iMnQiHS_nzWdnmG9jx3oX8HY93wEbO7LfNvJHZtSO2hFZFyGUeABP64z0SiBjduN2mtLhutBaolS1yGhIp5nvQLNw1OIu46M5Uq974Irl8Z5zGajZ6Al_veqnFN2p2mCBg4r93rpmyo2S7t0IylflgBXJNTYjr5PZvgkj-hMweMqyCwSoDObLpFazAMb4WxcmGVP65bFzJyfrdarInb-o5GDfVgxzINzKGqy0k6hMe6CNMEYRCIl3R67THlVrjbkCAwEAAaAVMBMGCSqGSIb3DQEJAjEGDAR0ZXN0MA0GCSqGSIb3DQEBCwUAA4IBAQAbXRocAbV7NXeiShgljj-XLA9humrOPWt7hXmILyC2m9fQOahq3zvOIY8o0VIMnI7o-uvKNIdLzMNeHQKwoCUZkpooRQRW8gR4Dbno5xPLzBl7oZXwdIGHmDaz6t2USK8ncDpgripmtuhIFQD2hOoNV08gQvA2rzB3tWTkxZXBHXqVmklRoXrsR_CyXDQfi9FZQ-RAkOaQjiAwKMj1FYih3dRXEC0KRdGOIvp_XBbgL9yblmDOyp6q1F0KVVNRI3X6NqFhUM8QmAtV-PFtp8XeksG9xf2MQynXxjloN-oUiFNdvVmUYbrVGnHPfs_7K6Qo1bXfClTWYBL_Y4sBjkPs)

I can see the following
![image](https://user-images.githubusercontent.com/3809077/109184516-143ae500-775d-11eb-942d-537746b47c0c.png)

The SEQUENCE contains `CriAttribute` fields.

Looks to me this should be something like `Implicit<Option<ApplicationTag0<Asn1SetOf<CriAttribute>>>>`
You should use `Asn1SetOf` in `CriAttribute` as well.

Do you have doc for the attribute you're trying to implement? I tried to google for "hostname attribute certificate sign request" but couldn't find about it.

**Comment by Geobert** [comment] 2021-02-25 17:02
Hi, 

thank you again for your time :D 

The hostname should be in subject_alternative_name extension 

OK for Asn1SetOf, that left me to write `CriAttribute` then.

**Comment by Geobert** [comment] 2021-02-26 12:39
Me again,

I'm trying to implement Deserialize for:
```rust
pub struct CriAttribute {
    pub ty: ObjectIdentifierAsn1,
    pub values: Asn1SetOf<ExtensionValue>,
}
```

and I followed what's done for `Extension` and at the moment I have this:
```rust
impl<'de> de::Visitor<'de> for Visitor {
            type Value = CriAttribute;

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("a valid DER-encoded algorithm identifier")
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
            where
                A: de::SeqAccess<'de>,
            {
                let ty: ObjectIdentifierAsn1 = seq_next_element!(seq, CriAttribute, "id");
                let values: Asn1SetOf<ExtensionValue> = seq_next_element!(seq, CriAttribute, "values");
               Ok(CriAttribute { ty, values })
            }
```

Of course it can't work as `ExtensionValue` is not `Deserializable`.

But I can't impl for `ExtensionValue` as it needs the oid to do so…

I'm not really familiar with writing serde's deserializer, how can I manage the deserializing of the ExtensionValues in the Asn1SetOf, from the Visitor of CriAttribute?

**Comment by Geobert** [comment] 2021-02-26 16:09
Maybe it's not that simple. We have a tool that generate CSR and the `attributes` looks like this:
![image](https://user-images.githubusercontent.com/72570/109322546-54c45c80-784a-11eb-9a7d-675b9a914e13.png)
`CRIAttribute` in the RFC is defined as :
```
CRIAttributes  ATTRIBUTE  ::= {
        ... -- add any locally defined attributes here -- }
```

and we have
> The values of type Attributes{} allowed for attributes are constrained to the values specified by the information object set CRIAttributes.

So `CriAttribute` might not be `Implicit<Option<ApplicationTag0<Asn1SetOf<CriAttribute>>>>` after all, but
`Implicit<Option<ApplicationTag0<CriAttributes>>>` (emphasis on the plural of `CriAttributes`)

and it seems that CriAttributes possible values are defined in https://tools.ietf.org/html/rfc2985#page-16

**Comment by CBenoit** [comment] 2021-02-26 22:49
Good job so far.
Let me elaborate.

RFC states

> attributes    [0] Attributes{{ CRIAttributes }}

As such ```Implicit<Option<ApplicationTag0<Asn1SetOf<Attribute>>>>``` itself is correct but you may add
```rust
pub type Attributes = Asn1SetOf<Attribute>
```
and write ```Implicit<Option<ApplicationTag0<Attributes>>>``` if you wish.

It occurred to me that these should not be named `CriAttributes` or `CriAttribute` to avoid confusion.

This

> attributes    [0] Attributes{{ CRIAttributes }}

means that the SET is constrained by some `CRIAttributes`: only attributes specified inside `CRIAttributes` may be used. Definition is provided by the RFC you provided: https://tools.ietf.org/html/rfc2985#page-16
This object will not appear in the code, instead we will just maintain an enum similar to what's done with [`AttributeTypeAndValue`](https://github.com/Devolutions/picky-rs/blob/master/picky-asn1-x509/src/attribute_type_and_value.rs#L22). For now you may add support for your use case only if you wish.
The enum itself is not directly serializable / deserializable because you can't know what is the correct variant unless you also have the corresponding OID. However, values contained by variants should be serializable / deserializable.

```rust
#[derive(Debug, PartialEq, Clone)]
enum AttributeValue {
    Extensions(Asn1SetOf<Extensions>), // this set will only ever contain one element
    // ... may contains other attributes
    Custom(picky_asn1_der::Asn1RawDer), // fallback case that user may process manually
}
```

Your _current_ `CriAttribute` becomes
```rust
pub struct Attribute {
    pub ty: ObjectIdentifierAsn1,
    pub value: AttributeValue,
}
```

In your `Deserialize` implementation you'll check the OID and de-serialize accordingly in the right variant.

Something similar to:

```rust
impl<'de> de::Visitor<'de> for Visitor {
            type Value = Attribute;

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("a valid DER-encoded attribute")
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
            where
                A: de::SeqAccess<'de>,
            {
                let ty: ObjectIdentifierAsn1 = seq_next_element!(seq, AttributeTypeAndValue, "type oid");

                let value =
                    match Into::<String>::into(&ty.0).as_str() {
                        oids::EXTENSION_REQUEST => AttributeValue::Extensions(seq_next_element!(
                            seq,
                            AttributeTypeAndValue,
                            "at extension request"
                        )),
                        _ => AttributeValue::Custom(seq_next_element!(
                            seq,
                            Attribute,
                            "at custom value"
                        )),
                    };

                Ok(Attribute { ty, value })
            }
}
```

Does it sounds good to you?

**Comment by Geobert** [comment] 2021-03-01 10:37
Hi,

Thank you for this detailed answer!

After thinking about it the week-end, and reading your explanation, it makes sense!

**Comment by CBenoit** [comment] 2021-03-03 22:22
@Geobert #79 should provides the API in `picky` crate but could you confirm it works for you?

You need to allow extensions inheritance with `inherit_extensions_from_csr_attributes`:

```rust
let extensions = vec![Extension::new_subject_alt_name(vec![GeneralName::DNSName(
    IA5String::from_string("localhost".into()).unwrap().into(),
)])
.into_non_critical()];
let attr = Attribute::new_extension_request(extensions);
let csr = Csr::generate_with_attributes(
    DirectoryName::new_common_name("My Leaf Name"),
    &leaf_key,
    SignatureAlgorithm::RsaPkcs1v15(HashAlgorithm::SHA2_256),
    vec![attr],
)
.unwrap();

let signed_leaf = CertificateBuilder::new()
    .validity(UTCDate::ymd(2069, 1, 1).unwrap(), UTCDate::ymd(2072, 1, 1).unwrap())
    .subject_from_csr(csr)
    .issuer_cert(&root, &root_key)
    .inherit_extensions_from_csr_attributes(true)
    .build()
    .unwrap();
```

**Comment by Geobert** [comment] 2021-03-04 10:23
Thank you for making my changes from pick-asn1-x509 available on a higher level of abstraction :)

I don't need the CertificateBuilder because I'm using picky only to generate the CSR. The certificate is being emitted by another tool already written a long time ago, but that's a nice addition to have anyway if ever it's needed.

**Comment by Geobert** [comment] 2021-03-04 12:17
I don't understand the error above, the bound seems to be satisfied, maybe it's some kind of compatibility issue using the branch?

**Comment by CBenoit** [comment] 2021-03-04 13:57
Make sure you're using not only `picky-asn1` but also `picky-asn1-x509` from the right branch
I think I should build an abstraction around Attribute to avoid this kind of confusion, I have to admit this kind of error is not quite clear :sweat:

**Comment by Geobert** [comment] 2021-03-04 14:03
> 
> 
> Make sure you're using not only `picky-asn1` but also `picky-asn1-x509` from the right branch
> I think I should build an abstraction around Attribute to avoid this kind of confusion, I have to admit this kind of error is not quite clear 😓

Thanks for your answer!

Well, as said in the EDIT (you might have missed them), I've rolled back to picky 6.1.2 to test, and I have the same error:
```rust
use picky::{
    signature::SignatureAlgorithm,
    x509::{
        name::{GeneralName, NameAttr},
        Extension,
    },
};

fn test() {
let n = GeneralName::new_dns_name("localhost").expect("invalid name string");

        let extension =
            Extension::new_subject_alt_name::<Vec<GeneralName>>(vec![n]).into_non_critical();
}
```

**Comment by CBenoit** [comment] 2021-03-04 14:23
> > Make sure you're using not only `picky-asn1` but also `picky-asn1-x509` from the right branch
> > I think I should build an abstraction around Attribute to avoid this kind of confusion, I have to admit this kind of error is not quite clear sweat
> 
> Thanks for your answer!
> 
> Well, as said in the EDIT (you might have missed them), I've rolled back to picky 6.1.2 to test, and I have the same error:
> 
> ```rust
> use picky::{
>     signature::SignatureAlgorithm,
>     x509::{
>         name::{GeneralName, NameAttr},
>         Extension,
>     },
> };
> 
> fn test() {
> let n = GeneralName::new_dns_name("localhost").expect("invalid name string");
> 
>         let extension =
>             Extension::new_subject_alt_name::<Vec<GeneralName>>(vec![n]).into_non_critical();
> }
> ```

Oh sorry, I see what's the problem. Actually you can make it work by using `picky::x509::name::GeneralNames`:
```rust
let names = GeneralNames::new(n);
```
The issue is that `picky::x509::name::GeneralName` doesn't implement `Into<picky-asn1-x509::GeneralNames>`. I pushed a fix in the branch, maybe you can try to run `cargo update -p picky` and confirm it works?

**Comment by Geobert** [comment] 2021-03-04 14:33
Thank you again!

it works with `let names = GeneralNames::new(n);`, but not without it (in the branch)

**Comment by Geobert** [comment] 2021-03-04 14:43
But that doesn't work for multiple subject_alt_name, does it?

```rust
let n = GeneralName::new_dns_name("localhost").expect("invalid name string");
        let n2 = GeneralName::new_dns_name("second").expect("invalid name string");

        let extension = Extension::new_subject_alt_name(vec![n, n2]).into_non_critical();
```

**Comment by CBenoit** [comment] 2021-03-04 14:50
> But that doesn't work for multiple subject_alt_name, does it?
> 
> ```rust
> let n = GeneralName::new_dns_name("localhost").expect("invalid name string");
>         let n2 = GeneralName::new_dns_name("second").expect("invalid name string");
> 
>         let extension = Extension::new_subject_alt_name(vec![n, n2]).into_non_critical();
> ```

Right it doesn't, you need to write
```rust
use picky::x509::{name::GeneralName, Extension};

fn main() {
    let n = GeneralName::new_dns_name("localhost").expect("invalid name string");
    let _ = Extension::new_subject_alt_name(n).into_non_critical();
}
```
or
```rust
use picky::x509::{name::GeneralName, name::GeneralNames, Extension};

fn main() {
    let n = GeneralName::new_dns_name("localhost").expect("invalid name string");
    let n2 = GeneralName::new_dns_name("second").expect("invalid name string");
    let mut names = GeneralNames::new(n);
    names.add_name(n2);

    let _ = Extension::new_subject_alt_name(names).into_non_critical();
}
```
I can't implement `Into<picky-asn1-x509::GeneralNames>` on `Vec<GeneralName>` because of the orphan rule…
Also `GeneralNames::new_dns_name` already exists, but I'll improve a bit API so you can do
```rust
    let names = GeneralNames::new_dns_name("localhost").with_dns_name("second");
    let _ = Extension::new_subject_alt_name(names).into_non_critical();
```

**Comment by Geobert** [comment] 2021-03-04 15:05
> I can't implement `Into<picky-asn1-x509::GeneralNames>` on `Vec<GeneralName>` because of the orphan rule…
> Also `GeneralNames::new_dns_name` already exists, but I'll improve a bit API so you can do
> 
> ```rust
>     let names = GeneralNames::new_dns_name(IA5String::new("localhost").unwrap())
>         .with_dns_name(IA5String::new("second").unwrap());
>     let _ = Extension::new_subject_alt_name(names).into_non_critical();
> ```
> 
> or
> 
> ```rust
>     let n = GeneralName::new_dns_name("localhost").expect("invalid name string");
>     let n2 = GeneralName::new_dns_name("second").expect("invalid name string");
>     let names = GeneralNames::from(vec![n, n2]);
>     let _ = Extension::new_subject_alt_name(names).into_non_critical();
> ```

I prefer the second one :) I'm parsing a `Vec<String>` and transform it to `GeneralNames`
With the second form, I could map the `Vec<String>` to `Vec<GeneralName>` and then use `GeneralNames::from()`

**Comment by Geobert** [comment] 2021-03-04 15:20
We might need a reexport of `picky_asn1_x509::Attribute` in `picky`?

**Comment by CBenoit** [comment] 2021-03-04 15:35
> We might need a reexport of `picky_asn1_x509::Attribute` in `picky`?

You're right, I did that, so this now gives us
```rust
use crate::x509::name::{GeneralName, DirectoryName};
use crate::x509::csr::{Csr, Attribute};
use crate::x509::Extension;
use crate::hash::HashAlgorithm;
use crate::signature::SignatureAlgorithm;

let dns_name = GeneralName::new_dns_name("localhost").unwrap();
let extensions = vec![Extension::new_subject_alt_name(dns_name).into_non_critical()];
let attr = Attribute::new_extension_request(extensions);
let csr = Csr::generate_with_attributes(
    DirectoryName::new_common_name("I want more extensions"),
    &leaf_key,
    SignatureAlgorithm::RsaPkcs1v15(HashAlgorithm::SHA2_256),
    vec![attr],
)
.unwrap();
```

I also updated `GeneralNames` so it supports above-mentioned constructions. :+1: 

With that I think I can merge and publish a new version on crates.io :slightly_smiling_face:

**Comment by Geobert** [comment] 2021-03-04 15:38
Let me finish using it to be sure :)

**Comment by Geobert** [comment] 2021-03-04 15:46
Just to be sure it's not an oversight:
I don't know if you remember a previous talk we had about the order of element in a DirectoryName
When parsing a string "cn=name,c=xx" I had to `.rev()` in order to have the element in the correct order for our CSR processor tool.

Well now I had to remove the °.rev()` to make it the correct order. 

No big deal, just wanted to point it out to be sure there's no issue here

**Comment by CBenoit** [comment] 2021-03-04 15:52
> Just to be sure it's not an oversight:
> I don't know if you remember a previous talk we had about the order of element in a DirectoryName
> When parsing a string "cn=name,c=xx" I had to `.rev()` in order to have the element in the correct order for our CSR processor tool.
> 
> Well now I had to remove the °.rev()` to make it the correct order.
> 
> No big deal, just wanted to point it out to be sure there's no issue here

I think produced string has always been in the same order that items were added as demonstrated by [this test](https://github.com/Devolutions/picky-rs/blob/master/picky/src/x509/name.rs#L222). Can you send me the snippet exposing this behavior?

**Comment by Geobert** [comment] 2021-03-04 16:10
you should have a mail on you fried-world address :)

**Comment by CBenoit** [comment] 2021-03-04 16:53
As discussed by mail the code was working as expected with picky 6.0, 6.1 and (future) 6.2, so I'll go forward with merging and close the issue. If you ever figure out why your code previously worked with `.rev()` let me know :slightly_smiling_face: 
Thank you for your help!

**Closed** 2021-03-04 17:17 UTC

**Comment by Geobert** [comment] 2021-03-05 11:20
> why your code previously worked with `.rev()` let me know

I still need .rev() for the CSR to be used correctly with our tool :) My test was wrong ^^'
