### ISSUE TITLE
Improper encoding of JWK for RSA keys (The JWK "n" member contained a leading zero.)

### ISSUE THREAD

**Issue by wellcaffeinated** [Devolutions/picky-rs#140] opened 2022-04-01 23:51 UTC
Affected version picky 6.3.0

Problem: When attempting to use the JWK that picky created in chrome, i get this error:

> DOMException: The JWK "n" member contained a leading zero.

This is related to the following:
* https://github.com/anvilresearch/connect-js/issues/7
* https://github.com/OADA/rsa-pem-to-jwk/issues/1
* https://bugs.chromium.org/p/chromium/issues/detail?id=383998

For what it's worth, i was doing this:

```rs
let pk = picky::key::PublicKey::from_rsa_der(&der)?;
let mut jwk = picky::jose::jwk::Jwk::from_public_key(&pk)?
jwk.alg = Some(picky::jose::jwk::Jwa::Sig(picky::jose::jws::JwsAlg::RS256));
```

And it gave me the output:
```json
{
  "alg": "RS256",
  "e": "AQAB",
  "kty": "RSA",
  "n": "ANA4_xFppBBf56Vcbt2CRQTe35qaGzFvo30mIpuwJjAP9H1lhoGwWPAISL9f0unC4zPIZWsOf8xSXGSgjLYJkguPUph17qznKZZ1hH2Wbti-2ES-1M_MJS4x6oC2v-9UmE6xV1mVI6mepBwqrKMY2Fe2HZWS1zk7FKnWmPz_dIbzZyP8ctrbHFyZqgJCJjSLHwO6Lzh0K4cGdMn6WGnzgj6rYj65qDTSvTXoToSxHDUeOYoVn0ERqzm-DinJlXGYyE-Ucqkx7u7nqWSQysE1G8zlUVQ5ilv38FfHf2Gi7rI7k3PxBNWNme95UADzlYQGUtW-YpTkR9Mfsd4-wliA5Yc"
}
```

Note the leading zero: `ANA4_xFpp...`

**Comment by CBenoit** [comment] 2022-04-04 13:47
Thank you for reporting this!

**Comment by CBenoit** [comment] 2022-04-07 21:03
@wellcaffeinated could you confirm the issue is fixed on your side as well when using the patch from #141?
In you `Cargo.toml`:
```toml
picky = { git = "https://github.com/Devolutions/picky-rs", rev = "5f1862f7a8f3f5f21e28a801377b3e926e133f97", … }
```
Thank you!

**Comment by wellcaffeinated** [comment] 2022-04-08 16:50
Hmm.... I'm having some trouble with conflicting versions now

```
error: failed to select a version for `zeroize`.
    ... required by package `num-bigint-dig v0.8.1`
    ... which satisfies dependency `num-bigint-dig = "^0.8.1"` of package `picky v7.0.0-rc.2 (https://github.com/Devolutions/picky-rs?rev=5f1862f7a8f3f5f21e28a801377b3e926e133f97#5f1862f7)`
    ... which satisfies git dependency `picky` of package `hsm-bridge v0.1.0 (/Users/wellcaffeinated/Documents/github/buffbeacon/twine-ipfs/beacon/hsm-bridge)`
versions that meet the requirements `^1.5` are: 1.5.4, 1.5.3

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.3.0`
    ... which satisfies dependency `zeroize = "^1"` (locked to 1.3.0) of package `crypto-bigint v0.3.2`
    ... which satisfies dependency `crypto-bigint = "^0.3"` (locked to 0.3.2) of package `der v0.5.1`
    ... which satisfies dependency `der = "^0.5"` (locked to 0.5.1) of package `ecdsa v0.13.4`
    ... which satisfies dependency `ecdsa-core = "^0.13"` (locked to 0.13.4) of package `p256 v0.10.1`
    ... which satisfies dependency `p256 = "^0.10"` (locked to 0.10.1) of package `yubihsm v0.40.0`
    ... which satisfies dependency `yubihsm = "^0.40"` (locked to 0.40.0) of package `hsm-bridge v0.1.0 (/Users/wellcaffeinated/Documents/github/buffbeacon/twine-ipfs/beacon/hsm-bridge)`

failed to select a version for `zeroize` which could resolve this conflict
```

**Comment by CBenoit** [comment] 2022-04-08 18:53
Maybe you could try update your Cargo.lock with
```
$ cargo update -p zeroize
```

**Comment by wellcaffeinated** [comment] 2022-04-08 20:53
no dice :(

```
error: failed to select a version for `zeroize`.
    ... required by package `curve25519-dalek v3.2.1`
    ... which satisfies dependency `curve25519-dalek = "^3"` (locked to 3.2.1) of package `ed25519-dalek v1.0.1`
    ... which satisfies dependency `ed25519-dalek = "^1"` (locked to 1.0.1) of package `yubihsm v0.40.0`
    ... which satisfies dependency `yubihsm = "^0.40"` (locked to 0.40.0) of package `hsm-bridge v0.1.0 (/Users/wellcaffeinated/Documents/github/buffbeacon/twine-ipfs/beacon/hsm-bridge)`
versions that meet the requirements `>=1, <1.4` are: 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.5.3`
    ... which satisfies dependency `zeroize = "^1.5"` of package `num-bigint-dig v0.8.1`
    ... which satisfies dependency `num-bigint-dig = "^0.8.1"` of package `picky v7.0.0-rc.2 (https://github.com/Devolutions/picky-rs?rev=5f1862f7a8f3f5f21e28a801377b3e926e133f97#5f1862f7)`
    ... which satisfies git dependency `picky` of package `hsm-bridge v0.1.0 (/Users/wellcaffeinated/Documents/github/buffbeacon/twine-ipfs/beacon/hsm-bridge)`

failed to select a version for `zeroize` which could resolve this conflict
```

**Comment by CBenoit** [comment] 2022-04-09 04:05
Oh, the error changed and is actually showing something useful!
Looks like `curve25519-dalek` is depending on `zeroize >= 1, <1.4`, but since `num-bigint-dig` is depending on `zeroize ^1.5`, there is no version that can be used by both :/

Here are some relevant links:

- https://github.com/dalek-cryptography/curve25519-dalek/issues/362
- https://github.com/dalek-cryptography/curve25519-dalek/commit/b6a7406c7340d8236be449fa0372c0373a2f7876#r65843797

I understand `curve25519-dalek` did that because they have a different policy about MSRV.

Now, there is no good solution in such case, ideally `curve25519-dalek` could bump their MSRV. There is a patch for just that you could use: https://github.com/dalek-cryptography/curve25519-dalek/pull/386

**Comment by hariria** [comment] 2022-04-13 22:18
@CBenoit  any updates on this? Any chance we can bump the MSRV?

**Closed** 2022-04-20 13:52 UTC
Labels: bug
